---
title: 'S01: Introduction to R for Data Science'
subtitle: 'Session 01: Introduction to R from RStudio IDE'
author: "Goran S. Milovanovic"
date: "November 5, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Lecturers

#### [Goran S. Milovanović](http://www.exactness.net), Phd, Data Science Mentor at [Springboard](https://www.springboard.com/workshops/data-science), [Data Science Serbia](http://www.datascience.rs)
#### [ing Branko Kovač](https://rs.linkedin.com/in/kovacbranko), Data Scientist @Tradecore, Data Science Mentor at [Springboard](https://www.springboard.com/workshops/data-science), [Data Science Serbia](http://www.datascience.rs)

```{r echo=T}
# clear workspace
rm(list=ls())
# try this out:
ls()
```

```{r echo=T}
# R as a calculator
2+2
2/3-1+5
a <- 1/3
b = 7
a + b
```

```{r echo=T}
# what is my working directory?
getwd()
```

```{r echo=T}
# save R object as .rds file
saveRDS(a, "a.rds")
a <- readRDS("a.rds")
```

```{r echo=T}
# save several R objects as .RData file
save(list = c("a", "b"), file = "obj.RData")

# remove a, b
rm(a,b)
getwd()
# load .RDatafile to R
load(file = "obj.RData")
```

```{r echo=T}
# list of loaded objects
ls()

# remove all objects
rm(list=ls())
```


```{r echo=F}
# installing packages:
# install.packages("dplyr") # replace "dplyr" with other package name
installed.packages() # list of installed packages
```

```{r echo=T}
# The shape of things to come:
numbers <- c(1,2,3,4,5)
words <- c("data", "science", "r")
boolean <- c(TRUE, FALSE)
data("mtcars")
```

---
#### [Data Science Serbia](http://www.datascience.rs)
---
